# Generated by Django 4.0.1 on 2023-02-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='landing',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterField(
            model_name='landing',
            name='content',
            field=models.TextField(blank=True, verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликованно'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='photo',
            field=models.ImageField(upload_to='photos/&Y/%m/%d/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='landing',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='landing.category'),
        ),
    ]
