# Generated by Django 4.0.1 on 2023-02-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_category_alter_landing_options_alter_landing_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='friends',
            field=models.ManyToManyField(to='landing.landing'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landing.category'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='photo',
            field=models.URLField(blank=True, max_length=255, verbose_name='Изображения'),
        ),
    ]
