# Generated by Django 4.0.1 on 2023-02-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_brick_alter_landing_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='landing.Brick'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='landing.Brick'),
        ),
    ]
