# Generated by Django 4.0.1 on 2023-02-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_remove_landing_cat_remove_landing_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('type_file', models.TextField(blank=True, choices=[('image', 'Изображения'), ('doc', 'Документ'), ('vido', 'Видео'), ('audio', 'Аудио')], verbose_name='Тип файла')),
                ('data', models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='Фаил')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликованно')),
            ],
            options={
                'verbose_name': 'Фаил',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
