# Generated by Django 4.0.1 on 2023-02-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Фамилия')),
                ('mail', models.CharField(db_index=True, max_length=100, verbose_name='Почта')),
                ('tel', models.CharField(db_index=True, max_length=100, verbose_name='Телефон')),
                ('which', models.CharField(db_index=True, max_length=100, verbose_name='Форма отправки')),
                ('ip', models.CharField(db_index=True, max_length=100, verbose_name='IP')),
                ('country', models.CharField(db_index=True, max_length=100, verbose_name='Страна')),
                ('os', models.CharField(db_index=True, max_length=100, verbose_name='Операционная система')),
                ('browser', models.CharField(db_index=True, max_length=100, verbose_name='Браузер')),
                ('data', models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='Фаил')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('status', models.TextField(blank=True, choices=[('new', 'Новая'), ('processing', 'Обработка'), ('completed', 'Завершенна')], verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
