# Generated by Django 4.0.1 on 2023-02-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='message',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Сообщение'),
        ),
    ]
