# Generated by Django 4.0.1 on 2023-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_bids_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='browser',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Браузер'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='data',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Фаил'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='mail',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='message',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='os',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='tel',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='which',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Форма отправки'),
        ),
    ]
