# Generated by Django 4.0.1 on 2023-02-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_landing_order_alter_bids_browser_alter_bids_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='type_block',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип'),
        ),
    ]
