# Generated by Django 4.0.1 on 2023-02-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_landing_type_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='type_block',
            field=models.CharField(blank=True, choices=[('themes', 'Типизированный'), ('null', 'Пустой'), ('html', 'Произвольный'), ('js', 'JS'), ('scc', 'Cтили')], max_length=255, null=True, verbose_name='Тип'),
        ),
    ]
