# Generated by Django 4.1.6 on 2023-03-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_landing_name_alter_landing_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='IP')),
                ('browser', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Браузер')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время посещения')),
                ('time_out', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Время ухода')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
            },
        ),
    ]
